# Generated by Django 4.1.7 on 2023-02-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='categorie',
            old_name='category',
            new_name='name',
        ),
    ]
