# Generated by Django 4.1.7 on 2023-02-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
    ]
